# Generated by Django 4.2.2 on 2023-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orquestra',
            name='musicos',
            field=models.ManyToManyField(to='core.musico'),
        ),
    ]
