# Generated by Django 4.2.2 on 2023-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orquestra_musicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='dt_apresentacao',
            field=models.DateTimeField(),
        ),
    ]
