# Generated by Django 4.2.2 on 2023-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apresentacao_dt_apresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='hr_apresentacao',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='dt_apresentacao',
            field=models.DateField(),
        ),
    ]
